# Copyright (C) 2019-2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/realme/RMX1911/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/realme/RMX1911/proprietary/bin/dpmd:system/bin/dpmd \
    vendor/realme/RMX1911/proprietary/etc/dpm/dpm.conf:system/etc/dpm/dpm.conf \
    vendor/realme/RMX1911/proprietary/etc/init/dpmd.rc:system/etc/init/dpmd.rc \
    vendor/realme/RMX1911/proprietary/etc/permissions/cneapiclient.xml:system/etc/permissions/cneapiclient.xml \
    vendor/realme/RMX1911/proprietary/etc/permissions/com.qti.dpmframework.xml:system/etc/permissions/com.qti.dpmframework.xml \
    vendor/realme/RMX1911/proprietary/etc/permissions/com.qualcomm.qti.imscmservice-V2.0-java.xml:system/etc/permissions/com.qualcomm.qti.imscmservice-V2.0-java.xml \
    vendor/realme/RMX1911/proprietary/etc/permissions/com.qualcomm.qti.imscmservice-V2.1-java.xml:system/etc/permissions/com.qualcomm.qti.imscmservice-V2.1-java.xml \
    vendor/realme/RMX1911/proprietary/etc/permissions/com.qualcomm.qti.imscmservice.xml:system/etc/permissions/com.qualcomm.qti.imscmservice.xml \
    vendor/realme/RMX1911/proprietary/etc/permissions/com.quicinc.cne.xml:system/etc/permissions/com.quicinc.cne.xml \
    vendor/realme/RMX1911/proprietary/etc/permissions/dpmapi.xml:system/etc/permissions/dpmapi.xml \
    vendor/realme/RMX1911/proprietary/etc/permissions/embms.xml:system/etc/permissions/embms.xml \
    vendor/realme/RMX1911/proprietary/etc/permissions/privapp-permissions-qti.xml:system/etc/permissions/privapp-permissions-qti.xml \
    vendor/realme/RMX1911/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/realme/RMX1911/proprietary/etc/permissions/telephonyservice.xml:system/etc/permissions/telephonyservice.xml \
    vendor/realme/RMX1911/proprietary/etc/permissions/vendor.qti.hardware.data.connection-V1.0-java.xml:system/etc/permissions/vendor.qti.hardware.data.connection-V1.0-java.xml \
    vendor/realme/RMX1911/proprietary/etc/sysconfig/qti_whitelist.xml:system/etc/sysconfig/qti_whitelist.xml \
    vendor/realme/RMX1911/proprietary/framework/vendor.qti.hardware.alarm-V1.0-java.jar:system/framework/vendor.qti.hardware.alarm-V1.0-java.jar \
    vendor/realme/RMX1911/proprietary/lib/com.qualcomm.qti.ant@1.0.so:system/lib/com.qualcomm.qti.ant@1.0.so \
    vendor/realme/RMX1911/proprietary/lib/com.qualcomm.qti.dpm.api@1.0.so:system/lib/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/realme/RMX1911/proprietary/lib/com.qualcomm.qti.imscmservice@1.0.so:system/lib/com.qualcomm.qti.imscmservice@1.0.so \
    vendor/realme/RMX1911/proprietary/lib/com.qualcomm.qti.imscmservice@2.0.so:system/lib/com.qualcomm.qti.imscmservice@2.0.so \
    vendor/realme/RMX1911/proprietary/lib/com.qualcomm.qti.imscmservice@2.1.so:system/lib/com.qualcomm.qti.imscmservice@2.1.so \
    vendor/realme/RMX1911/proprietary/lib/com.qualcomm.qti.uceservice@2.0.so:system/lib/com.qualcomm.qti.uceservice@2.0.so \
    vendor/realme/RMX1911/proprietary/lib/com.quicinc.cne.api@1.0.so:system/lib/com.quicinc.cne.api@1.0.so \
    vendor/realme/RMX1911/proprietary/lib/com.quicinc.cne.api@1.1.so:system/lib/com.quicinc.cne.api@1.1.so \
    vendor/realme/RMX1911/proprietary/lib/com.quicinc.cne.constants@1.0.so:system/lib/com.quicinc.cne.constants@1.0.so \
    vendor/realme/RMX1911/proprietary/lib/com.quicinc.cne.constants@2.0.so:system/lib/com.quicinc.cne.constants@2.0.so \
    vendor/realme/RMX1911/proprietary/lib/com.quicinc.cne.constants@2.1.so:system/lib/com.quicinc.cne.constants@2.1.so \
    vendor/realme/RMX1911/proprietary/lib/com.quicinc.cne.server@1.0.so:system/lib/com.quicinc.cne.server@1.0.so \
    vendor/realme/RMX1911/proprietary/lib/com.quicinc.cne.server@2.0.so:system/lib/com.quicinc.cne.server@2.0.so \
    vendor/realme/RMX1911/proprietary/lib/com.quicinc.cne.server@2.1.so:system/lib/com.quicinc.cne.server@2.1.so \
    vendor/realme/RMX1911/proprietary/lib/com.quicinc.cne.server@2.2.so:system/lib/com.quicinc.cne.server@2.2.so \
    vendor/realme/RMX1911/proprietary/lib/com.quicinc.cne.server@2.3.so:system/lib/com.quicinc.cne.server@2.3.so \
    vendor/realme/RMX1911/proprietary/lib/lib-imsvideocodec.so:system/lib/lib-imsvideocodec.so \
    vendor/realme/RMX1911/proprietary/lib/lib-imsvt.so:system/lib/lib-imsvt.so \
    vendor/realme/RMX1911/proprietary/lib/lib-imsvtextutils.so:system/lib/lib-imsvtextutils.so \
    vendor/realme/RMX1911/proprietary/lib/lib-imsvtutils.so:system/lib/lib-imsvtutils.so \
    vendor/realme/RMX1911/proprietary/lib/libdiag_system.so:system/lib/libdiag_system.so \
    vendor/realme/RMX1911/proprietary/lib/libdpmctmgr.so:system/lib/libdpmctmgr.so \
    vendor/realme/RMX1911/proprietary/lib/libdpmfdmgr.so:system/lib/libdpmfdmgr.so \
    vendor/realme/RMX1911/proprietary/lib/libdpmframework.so:system/lib/libdpmframework.so \
    vendor/realme/RMX1911/proprietary/lib/libdpmtcm.so:system/lib/libdpmtcm.so \
    vendor/realme/RMX1911/proprietary/lib/libimscamera_jni.so:system/lib/libimscamera_jni.so \
    vendor/realme/RMX1911/proprietary/lib/libimsmedia_jni.so:system/lib/libimsmedia_jni.so \
    vendor/realme/RMX1911/proprietary/lib/librcc.so:system/lib/librcc.so \
    vendor/realme/RMX1911/proprietary/lib/libsdm-disp-apis.so:system/lib/libsdm-disp-apis.so \
    vendor/realme/RMX1911/proprietary/lib/vendor.qti.data.factory@1.0.so:system/lib/vendor.qti.data.factory@1.0.so \
    vendor/realme/RMX1911/proprietary/lib/vendor.qti.data.factory@1.1.so:system/lib/vendor.qti.data.factory@1.1.so \
    vendor/realme/RMX1911/proprietary/lib/vendor.qti.hardware.alarm@1.0.so:system/lib/vendor.qti.hardware.alarm@1.0.so \
    vendor/realme/RMX1911/proprietary/lib/vendor.qti.hardware.data.connection@1.0.so:system/lib/vendor.qti.hardware.data.connection@1.0.so \
    vendor/realme/RMX1911/proprietary/lib/vendor.qti.hardware.data.dynamicdds@1.0.so:system/lib/vendor.qti.hardware.data.dynamicdds@1.0.so \
    vendor/realme/RMX1911/proprietary/lib/vendor.qti.hardware.data.qmi@1.0.so:system/lib/vendor.qti.hardware.data.qmi@1.0.so \
    vendor/realme/RMX1911/proprietary/lib/vendor.qti.hardware.iop@1.0.so:system/lib/vendor.qti.hardware.iop@1.0.so \
    vendor/realme/RMX1911/proprietary/lib/vendor.qti.hardware.iop@2.0.so:system/lib/vendor.qti.hardware.iop@2.0.so \
    vendor/realme/RMX1911/proprietary/lib/vendor.qti.hardware.perf@1.0.so:system/lib/vendor.qti.hardware.perf@1.0.so \
    vendor/realme/RMX1911/proprietary/lib/vendor.qti.ims.callinfo@1.0.so:system/lib/vendor.qti.ims.callinfo@1.0.so \
    vendor/realme/RMX1911/proprietary/lib/vendor.qti.ims.rcsconfig@1.0.so:system/lib/vendor.qti.ims.rcsconfig@1.0.so \
    vendor/realme/RMX1911/proprietary/lib/vendor.qti.imsrtpservice@1.0.so:system/lib/vendor.qti.imsrtpservice@1.0.so \
    vendor/realme/RMX1911/proprietary/lib64/com.qualcomm.qti.ant@1.0.so:system/lib64/com.qualcomm.qti.ant@1.0.so \
    vendor/realme/RMX1911/proprietary/lib64/com.qualcomm.qti.dpm.api@1.0.so:system/lib64/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/realme/RMX1911/proprietary/lib64/com.qualcomm.qti.imscmservice@1.0.so:system/lib64/com.qualcomm.qti.imscmservice@1.0.so \
    vendor/realme/RMX1911/proprietary/lib64/com.qualcomm.qti.imscmservice@2.0.so:system/lib64/com.qualcomm.qti.imscmservice@2.0.so \
    vendor/realme/RMX1911/proprietary/lib64/com.qualcomm.qti.imscmservice@2.1.so:system/lib64/com.qualcomm.qti.imscmservice@2.1.so \
    vendor/realme/RMX1911/proprietary/lib64/com.qualcomm.qti.uceservice@2.0.so:system/lib64/com.qualcomm.qti.uceservice@2.0.so \
    vendor/realme/RMX1911/proprietary/lib64/com.quicinc.cne.api@1.0.so:system/lib64/com.quicinc.cne.api@1.0.so \
    vendor/realme/RMX1911/proprietary/lib64/com.quicinc.cne.api@1.1.so:system/lib64/com.quicinc.cne.api@1.1.so \
    vendor/realme/RMX1911/proprietary/lib64/com.quicinc.cne.constants@1.0.so:system/lib64/com.quicinc.cne.constants@1.0.so \
    vendor/realme/RMX1911/proprietary/lib64/com.quicinc.cne.constants@2.0.so:system/lib64/com.quicinc.cne.constants@2.0.so \
    vendor/realme/RMX1911/proprietary/lib64/com.quicinc.cne.constants@2.1.so:system/lib64/com.quicinc.cne.constants@2.1.so \
    vendor/realme/RMX1911/proprietary/lib64/com.quicinc.cne.server@1.0.so:system/lib64/com.quicinc.cne.server@1.0.so \
    vendor/realme/RMX1911/proprietary/lib64/com.quicinc.cne.server@2.0.so:system/lib64/com.quicinc.cne.server@2.0.so \
    vendor/realme/RMX1911/proprietary/lib64/com.quicinc.cne.server@2.1.so:system/lib64/com.quicinc.cne.server@2.1.so \
    vendor/realme/RMX1911/proprietary/lib64/com.quicinc.cne.server@2.2.so:system/lib64/com.quicinc.cne.server@2.2.so \
    vendor/realme/RMX1911/proprietary/lib64/com.quicinc.cne.server@2.3.so:system/lib64/com.quicinc.cne.server@2.3.so \
    vendor/realme/RMX1911/proprietary/lib64/lib-imsvideocodec.so:system/lib64/lib-imsvideocodec.so \
    vendor/realme/RMX1911/proprietary/lib64/lib-imsvt.so:system/lib64/lib-imsvt.so \
    vendor/realme/RMX1911/proprietary/lib64/lib-imsvtextutils.so:system/lib64/lib-imsvtextutils.so \
    vendor/realme/RMX1911/proprietary/lib64/lib-imsvtutils.so:system/lib64/lib-imsvtutils.so \
    vendor/realme/RMX1911/proprietary/lib64/libdiag_system.so:system/lib64/libdiag_system.so \
    vendor/realme/RMX1911/proprietary/lib64/libdpmctmgr.so:system/lib64/libdpmctmgr.so \
    vendor/realme/RMX1911/proprietary/lib64/libdpmfdmgr.so:system/lib64/libdpmfdmgr.so \
    vendor/realme/RMX1911/proprietary/lib64/libdpmframework.so:system/lib64/libdpmframework.so \
    vendor/realme/RMX1911/proprietary/lib64/libdpmtcm.so:system/lib64/libdpmtcm.so \
    vendor/realme/RMX1911/proprietary/lib64/libimscamera_jni.so:system/lib64/libimscamera_jni.so \
    vendor/realme/RMX1911/proprietary/lib64/libimsmedia_jni.so:system/lib64/libimsmedia_jni.so \
    vendor/realme/RMX1911/proprietary/lib64/librcc.so:system/lib64/librcc.so \
    vendor/realme/RMX1911/proprietary/lib64/libsdm-disp-apis.so:system/lib64/libsdm-disp-apis.so \
    vendor/realme/RMX1911/proprietary/lib64/vendor.display.color@1.0.so:system/lib64/vendor.display.color@1.0.so \
    vendor/realme/RMX1911/proprietary/lib64/vendor.display.color@1.1.so:system/lib64/vendor.display.color@1.1.so \
    vendor/realme/RMX1911/proprietary/lib64/vendor.display.color@1.2.so:system/lib64/vendor.display.color@1.2.so \
    vendor/realme/RMX1911/proprietary/lib64/vendor.qti.data.factory@1.0.so:system/lib64/vendor.qti.data.factory@1.0.so \
    vendor/realme/RMX1911/proprietary/lib64/vendor.qti.data.factory@1.1.so:system/lib64/vendor.qti.data.factory@1.1.so \
    vendor/realme/RMX1911/proprietary/lib64/vendor.qti.hardware.alarm@1.0.so:system/lib64/vendor.qti.hardware.alarm@1.0.so \
    vendor/realme/RMX1911/proprietary/lib64/vendor.qti.hardware.data.connection@1.0.so:system/lib64/vendor.qti.hardware.data.connection@1.0.so \
    vendor/realme/RMX1911/proprietary/lib64/vendor.qti.hardware.data.dynamicdds@1.0.so:system/lib64/vendor.qti.hardware.data.dynamicdds@1.0.so \
    vendor/realme/RMX1911/proprietary/lib64/vendor.qti.hardware.data.qmi@1.0.so:system/lib64/vendor.qti.hardware.data.qmi@1.0.so \
    vendor/realme/RMX1911/proprietary/lib64/vendor.qti.hardware.iop@1.0.so:system/lib64/vendor.qti.hardware.iop@1.0.so \
    vendor/realme/RMX1911/proprietary/lib64/vendor.qti.hardware.iop@2.0.so:system/lib64/vendor.qti.hardware.iop@2.0.so \
    vendor/realme/RMX1911/proprietary/lib64/vendor.qti.hardware.perf@1.0.so:system/lib64/vendor.qti.hardware.perf@1.0.so \
    vendor/realme/RMX1911/proprietary/lib64/vendor.qti.ims.callinfo@1.0.so:system/lib64/vendor.qti.ims.callinfo@1.0.so \
    vendor/realme/RMX1911/proprietary/lib64/vendor.qti.ims.rcsconfig@1.0.so:system/lib64/vendor.qti.ims.rcsconfig@1.0.so \
    vendor/realme/RMX1911/proprietary/lib64/vendor.qti.imsrtpservice@1.0.so:system/lib64/vendor.qti.imsrtpservice@1.0.so

PRODUCT_PACKAGES += \
    libantradio \
    QtiTelephonyService \
    datastatusnotification \
    embms \
    imssettings \
    uceShimService \
    CNEService \
    dpmserviceapp \
    ims \
    qcrilmsgtunnel \
    QtiTelephonyServicelibrary \
    cneapiclient \
    com.qti.dpmframework \
    com.qualcomm.qti.imscmservice-V2.0-java \
    com.qualcomm.qti.imscmservice-V2.1-java \
    com.qualcomm.qti.uceservice-V2.0-java \
    com.quicinc.cne.api-V1.0-java \
    com.quicinc.cne.api-V1.1-java \
    com.quicinc.cne.constants-V1.0-java \
    com.quicinc.cne.constants-V2.0-java \
    com.quicinc.cne.constants-V2.1-java \
    com.quicinc.cne \
    com.quicinc.cne.server-V1.0-java \
    com.quicinc.cne.server-V2.0-java \
    com.quicinc.cne.server-V2.1-java \
    com.quicinc.cne.server-V2.2-java \
    com.quicinc.cne.server-V2.3-java \
    dpmapi \
    embmslibrary \
    qcrilhook \
    tcmclient \
    vendor.qti.data.factory-V1.0-java \
    vendor.qti.data.factory-V1.1-java \
    vendor.qti.hardware.data.connection-V1.0-java \
    vendor.qti.hardware.data.dynamicdds-V1.0-java \
    vendor.qti.hardware.data.qmi-V1.0-java \
    vendor.qti.ims.callinfo-V1.0-java \
    vendor.qti.ims.rcsconfig-V1.0-java
